import type { NextPage } from "next";
import Head from "next/head";
import useSound from "use-sound";

const Home: NextPage = () => {
  const sounds = [
    "badumtss",
    "coin",
    "applause",
    "cricket",
    "drumroll",
    "gong",
    "sadtrombone",
    "cowsay",
    "booing",
    "cheering",
  ];
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form className="py-10 flex flex-wrap gap-5 max-w-6xl mx-auto">
        <input type="text" placeholder="User" className="rounded" />
        <input type="text" placeholder="Password" className="rounded" />
        <input type="submit" value="Connect" className="px-5 rounded" />
      </form>
      <div className="py-5 flex flex-wrap gap-20 max-w-6xl mx-auto">
        {sounds.map((s) => (
          <Sound key={s} name={s} />
        ))}
      </div>
    </div>
  );
};

export default Home;

function Sound({ name }: any) {
  const [play] = useSound(`/sounds/${name}.mp3`);

  return (
    <div
      onClick={() => play()}
      className="bg-red-100 w-36 h-36 rounded-3xl items-center justify-center cursor-pointer shadow-2xl flex hover:bg-blue-100"
    >
      {name}
    </div>
  );
}
